"""Configuration module for Multimodal RAG."""

from .settings import (
    LECTURES_DIR,
    IMAGE_OUTPUT_DIR,
    GENERATED_IMAGE_OUTPUT_DIR,
    VECTORSTORE_DIR,
    TEXT_EMBED_MODEL_NAME,
    DEVICE,
    IMAGE_MODEL_NAME,
    EMBED_DIM_TEXT,
    EMBED_DIM_IMAGE,
    TARGET_DIM,
    MIN_IMAGE_WIDTH,
    MIN_IMAGE_HEIGHT,
    MAX_ASPECT_RATIO,
    MIN_ASPECT_RATIO,
    MIN_FILE_SIZE,
    USE_CONTENT_BASED_NAMING,
    OPENAI_VISION_MODEL,
)

__all__ = [
    "LECTURES_DIR",
    "IMAGE_OUTPUT_DIR",
    "GENERATED_IMAGE_OUTPUT_DIR",
    "VECTORSTORE_DIR",
    "TEXT_EMBED_MODEL_NAME",
    "DEVICE",
    "IMAGE_MODEL_NAME",
    "EMBED_DIM_TEXT",
    "EMBED_DIM_IMAGE",
    "TARGET_DIM",
    "MIN_IMAGE_WIDTH",
    "MIN_IMAGE_HEIGHT",
    "MAX_ASPECT_RATIO",
    "MIN_ASPECT_RATIO",
    "MIN_FILE_SIZE",
    "USE_CONTENT_BASED_NAMING",
    "OPENAI_VISION_MODEL",
]

